---
- hosts: canary
  become: 'yes'
  vars:
    opencanary_dir: "/etc/opencanaryd/"
  tasks:
    - name: Install OpenCanary 
      include_role:
        name: ansible-role-opencanary
      vars:
        opencanary_version: master
        install_source: github
        portscan_enabled: "true"
        portscan_ignore_localhost: "true"
        ssh_enabled: "true"
        ssh_port: 2222
        ftp_enabled: "true"
        http_enabled: "true"
        https_enabled: "false"
        smb_enabled: "true"
        rdp_enabled: "true"
        ip_ignorelist:
          - 10.0.1.161/32

