---
- hosts: heron_gnd
  become: 'yes'
  tasks:
    - name: Install OpenVPN
      include_role:
        name: openvpn-client
      vars:
        openvpn_ufw: True
        ovpn_location: "~/Downloads/vpn.ovpn"

    - name: Install udev rules
      blockinfile:
        path: /etc/udev/rules.d/50-usb-utat.rules
        create: true
        block: |
          SUBSYSTEMS=="usb", KERNEL=="ttyACM*", ATTRS{idVendor}=="2341", ATTRS{idProduct}=="0042", MODE="0666", SYMLINK+="ttyRotator"
          SUBSYSTEMS=="usb", KERNEL=="ttyUSB*", ATTRS{idVendor}=="1a86", ATTRS{idProduct}=="7523", MODE="0666", SYMLINK+="ttyAmplifier"
          SUBSYSTEMS=="usb", KERNEL=="video*", ATTRS{idVendor}=="328f", ATTRS{idProduct}=="0073", SYMLINK+="vidExt"
      register: udev_rule

    - name: Restart udev
      shell: sudo udevadm control --reload-rules && sudo udevadm trigger
      when: udev_rule.changed

    - name: Install additional packages
      package:
        name:
          - gnuradio
          - tmux
          - uhubctl
          - usbtop
          - xrdp
          - ifmetric
          - v4l-utils
          - python3-ipython
          - htop


          # role for motion
